# Numpy Quizz

In [2]:
import numpy as np 

## Task 1: Array Creation and Basic Properties

*Key Concepts: Array creation, arange, linspace, array properties.*

- Create a 1D numpy array from a list with all integers between 10 and 100.
- Create an array of even numbers from 0 to 20.
- Generate an array with 10 equally spaced values between 0 and 1.
- Print the shape, size, and data type of each array.


In [ ]:
# solve the task here:

## Task 2: Array Manipulation with Random Data

*Key Concepts: Random arrays, indexing, reshaping, flattening.*

- Create a 3x4 array (`size=(3, 4)`) of random integers between 10 and 50.
- Index the array to access the element in the second row, third column.
- Reshape the array into a 2x6 array, then flatten it to a 1D array.
- Create a 2D array of shape (3, 4) with random numbers between 0 and 1.


In [ ]:
# solve the task here:

## Task 3: Simple Linear Algebra Operations

*Key Concepts: Linear algebra operations, element-wise and matrix multiplication, transpose, determinant.*

- Create two matrices, A and B. A has dimension (3,4) and consists of random choices of [10, 30, 50, 60] and B has dimension (4,2) and has random choices of [1,4,8,5,2].
- Perform element-wise multiplication of the first two rows and columns of A and B.
- Compute the addition of each row of A with the first column of B.
- Calculate the matrix product of A and B.

In [ ]:
# solve the task here:

## Solutions

In [ ]:
import numpy as np

# Task 1: Array Creation and Basic Properties
# -------------------------------------------

# Step 1: Create a 1D array from a list
array_from_list = np.array(list(range(10,101)))
print(f"Array from list:{array_from_list}")

# Step 2: Create an array of even numbers from 0 to 20
even_array = np.arange(0, 21, 2)
print(f"Array with even numbers from 0 to 20:{even_array}")

# Step 3: Generate an array with 10 equally spaced values between 0 and 1
linspace_array = np.linspace(0, 1, 10)
print(f"Linspace array:{linspace_array}")

# Step 4: Print shape, size, and dtype of each array
print(f"Properties of array_from_list - Shape:", array_from_list.shape, "Size:", array_from_list.size, "Dtype:", array_from_list.dtype)
print(f"Properties of even_array - Shape:", even_array.shape, "Size:", even_array.size, "Dtype:", even_array.dtype)
print(f"Properties of linspace_array - Shape:", linspace_array.shape, "Size:", linspace_array.size, "Dtype:", linspace_array.dtype)

# Task 2: Array Manipulation with Random Data
# -------------------------------------------

# Step 1: Create a 3x3 array of random integers between 10 and 50
random_array = np.random.randint(10, 50, size=(3, 4))
print(f"\n3x4 Random Integer Array:\n{random_array}")

# Step 2: Access element in the second row, third column
element = random_array[1, 2]
print(f"Element at [1, 2]:{element}")

# Step 3: Reshape the array to 1x9, then flatten it back to 1D
reshaped_array = random_array.reshape(2, 6)
flattened_array = reshaped_array.flatten()
print(f"Reshaped to 1x9:{reshaped_array}")
print(f"Flattened to 1D:{flattened_array}")

# Step 4: Create a 2D array of shape (3, 4) with random values between 0 and 1
random_array_2d = np.random.rand(3, 4)
print(f"\n3x4 Random Array:\n{random_array_2d}")

# Task 3: Simple Linear Algebra Operations
# ----------------------------------------

# Step 1: Create two 2x2 matrices A and B
A = np.random.choice([10,30,50,60], size=(3, 4))
B = np.random.choice([1,4,8,5,2], size=(4, 2))
print(f"\nMatrix A:\n{A}")
print(f"Matrix B:\n{B}")

# Step 2: Perform element-wise addition and multiplication
elementwise_multiplication = np.resize(A, (2,2)) * np.resize(B, (2,2))
print(f"Element-wise Addition:\n{elementwise_multiplication}")

# Step 3: Compute the addition of each row of A with the first column of B
addition_result = A + B[:,0].T
print(f"Addition of each row of A with the first column of B:\n{addition_result}")

# Step 4: Calculate the matrix product of A and B
matrix_product = np.dot(A, B)
print(f"Matrix Product of A and B:\n{matrix_product}")



Array from list:[1 2 3 4 5]
Array with even numbers from 0 to 20:[ 0  2  4  6  8 10 12 14 16 18 20]
Linspace array:[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Properties of array_from_list - Shape: (5,) Size: 5 Dtype: int64
Properties of even_array - Shape: (11,) Size: 11 Dtype: int64
Properties of linspace_array - Shape: (10,) Size: 10 Dtype: float64

3x4 Random Integer Array:
[[12 23 48 49]
 [29 15 48 31]
 [15 45 45 37]]
Element at [1, 2]:48
Reshaped to 1x9:[[12 23 48 49 29 15]
 [48 31 15 45 45 37]]
Flattened to 1D:[12 23 48 49 29 15 48 31 15 45 45 37]

3x4 Random Array:
[[0.78469744 0.13352081 0.04884846 0.6354755 ]
 [0.82202517 0.15116224 0.38581653 0.81543106]
 [0.35148978 0.20627624 0.73410106 0.60690666]]

Matrix A:
[[50 50 30 60]
 [10 30 30 10]
 [60 10 10 10]]
Matrix B:
[[1 2]
 [2 5]
 [5 4]
 [2 8]]
Element-wise Addition:
[[ 50 100]
 [ 60 300]]
Addition of each row of A with the first column of B:
[[51 52 35 62