# NumPy API

Previous examples were just the tip of the iceberg, for the full feature set, see [NumPy
user's Guide](https://numpy.org/doc/stable/user/index.html)

NumPy API is very popular and worth studying, and is mimicked by other popular libraries:
- TensorFlow
- PyTorch
- MXNet
- Numba
- CuPy
- Dask
- JAX
- NumExpr
- ...

A few more examples from NumPy:

In [1]:
import numpy as np


### Random numbers

In [2]:
np.random.randint(0, 20, size=5)


array([14,  4,  8,  8, 12])

In [3]:
np.random.seed(42)
np.random.randint(0, 20, size=5)


array([ 6, 19, 14, 10,  7])

### Regularly spaced values

In [4]:
# Integers, by spacing
np.arange(0, 50, 2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [5]:
# Floats, by spacing
np.arange(0, 2, 0.1)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [6]:
# Number of values over a given interval
np.linspace(start=0, stop=3, num=10)


array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

### Preallocating arrays

In [7]:
np.zeros(3)


array([0., 0., 0.])

In [8]:
np.zeros((3, 5), dtype=int)


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [9]:
np.ones(3)


array([1., 1., 1.])

In [10]:
np.ones((3, 5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Sums 

In [11]:
arr = np.array([1, 2, 3, 4, 5])


In [12]:
np.sum(arr)


15

In [13]:
# Vector of 0s and 1s
arr = np.array([1, 1, 1, 0, 0, 1])


In [14]:
# Count # of 1s and 0s
print("No. of 1s:", np.sum(arr))
print("No. of 0s:", np.sum(arr == 0))


No. of 1s: 4
No. of 0s: 2


In [15]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)


[[1 2 3]
 [4 5 6]]


In [16]:
# Column-wise sum
np.sum(A, axis=0)


array([5, 7, 9])

In [17]:
# Row-wise sum
np.sum(A, axis=1)


array([ 6, 15])